update:add validation functions to validate user input at init.ts script
xstevenyung/fresh-seo pull request #18
Opened 2022-10-07 15:22 UTC by sinyo-matu

## Background

In init.ts,
I think user input may need some validation to reduce unexpected or confusing behavior.

Move init.ts script contents into src/ may make our code cleaner
 
## What Changed
1. Adding two validation functions: `validateUrl` and `validateDir`
2. Moving init.ts script contents input src/intiFile.ts

2022-10-09 15:59 UTC, xstevenyung requested changes

2022-10-09 15:59 UTC, xstevenyung commented on src/initFile.ts
> +  if (!inputUrl || !isUrl(inputUrl.trim())) return "http://example.com";
I think I would rather throw an error here or even better display an error message and ask again for a prompt

2022-10-09 15:59 UTC, xstevenyung commented on src/initFile.ts
> +  if (!inputDir || inputDir.trim().length === 0) return "./static";
Same here as comment above

2022-10-10 14:01 UTC, xstevenyung approved these changes
Yeah I like this approach a lot, just some minor changes and we should be good to go

2022-10-10 14:01 UTC, xstevenyung commented on src/initFile.ts
> +    staticPath = ".static";
```suggestion
    staticPath = "./static";
```

2022-10-10 14:01 UTC, xstevenyung requested changes
Oops wrong button

2022-10-10 14:22 UTC, sinyo-matu commented on src/initFile.ts
> +    staticPath = ".static";
Thank you for pointing them out!

2022-10-12 11:07 UTC, sinyo-matu commented
@xstevenyung 
If you got time, please have a check!

2022-10-12 20:07 UTC, xstevenyung approved these changes

2022-10-12 20:08 UTC, xstevenyung commented
thanks a lot @sinyo-matu , amazing work ! 👍

2022-10-12 20:08 UTC, merged